# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0003_auto_20170103_0354'),
        ('workgroups', '0002_workgroup_library'),
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('due_date', models.DateField(null=True)),
                ('job_status', models.CharField(choices=[('APR', 'Approved'), ('REJ', 'Rejected'), ('PRO', 'Processing'), ('NPR', 'Not Processed'), ('EDT', 'Edit Required'), ('ASG', 'Assigned')], default='NPR', max_length=3)),
                ('priority', models.IntegerField(default=5)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('permissions', models.ManyToManyField(to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='TaggingJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.Job')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workgroups.WorkGroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging_jobs_given', to=settings.AUTH_USER_MODEL)),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobType')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging_jobs_taken', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
            bases=('jobs.job',),
        ),
    ]
