# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-12 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('view_job', 'Can view job'),)},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'permissions': (('view_jobtype', 'Can view job type'),)},
        ),
        migrations.AlterModelOptions(
            name='taggingjob',
            options={'permissions': (('view_taggingjob', 'Can view tagging job'),)},
        ),
    ]
