# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-19 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170112_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggingjob',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging_jobs', to='workgroups.WorkGroup'),
        ),
    ]
