# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-19 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0005_auto_20170115_1043'),
        ('jobs', '0003_auto_20170119_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggingjob',
            name='created_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagging_jobs_assigned', to='workgroups.WorkGroup'),
        ),
    ]
