# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-19 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_taggingjob_created_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggingjob',
            name='taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagging_jobs_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
