# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-04 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_scene_tag'),
        ('jobs', '0006_framejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='framejob',
            name='tags',
            field=models.ManyToManyField( to='tags.Tag'),
        ),
    ]
