# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-23 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20170505_0351'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_framejob_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoVideoJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.Job')),
                ('eta', models.FloatField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_video_jobs_given', to=settings.AUTH_USER_MODEL)),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobType')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
            options={
                'permissions': (('view_autovideojob', 'Can view auto video job'),),
            },
            bases=('jobs.job',),
        ),
    ]
