# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_autovideojob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('APR', 'Approved'), ('REJ', 'Rejected'), ('PRO', 'Processing'), ('NPR', 'Not Processed'), ('EDT', 'Edit Required'), ('ASG', 'Assigned'), ('PRD', 'Processed')], default='NPR', max_length=3),
        ),
    ]
