# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-24 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0009_auto_20170525_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleSyncJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.Job')),
                ('audio_file', models.URLField()),
                ('transcription', models.URLField()),
                ('eta', models.FloatField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_sync_jobs_given', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('jobs.job',),
        ),
    ]
