# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_subtitlesyncjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitlesyncjob',
            name='percent_complete',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
