# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_subtitlesyncjob_percent_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitlesyncjob',
            name='srt_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
