# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 05:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0013_audio_subtitle_transcription'),
        ('jobs', '0013_scriptprocessjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleTranslationJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.Job')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_translation_job_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_translation_job_given', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
            options={
                'permissions': (('view_subtitletranslationjob', 'Can view subtitle translation job'),),
            },
            bases=('jobs.job',),
        ),
    ]
