# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_subtitletranslationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitletranslationjob',
            name='source_subtitle',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtitletranslationjob',
            name='target_language',
            field=models.CharField(choices=[('FR', 'French'), ('SP', 'Spanish'), ('EN', 'English'), ('HI', 'Hindi')], default='EN', max_length=2),
        ),
    ]
