# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-06 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20180312_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('APR', 'Approved'), ('REJ', 'Rejected'), ('PRO', 'Processing'), ('NPR', 'Not Processed'), ('EDT', 'Edit Required'), ('ASG', 'Assigned'), ('PRD', 'Processed'), ('WIP', 'Work In Progress'), ('REV', 'Review'), ('QAP', 'Quality Assurance'), ('FAI', 'Job Failed')], default='NPR', max_length=3),
        ),
    ]
