# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-19 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20200106_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autovideojob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_video_jobs_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
