# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-27 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.URLField(blank=True, null=True)),
                ('final_file', models.URLField(blank=True, null=True)),
                ('channel', models.CharField(max_length=128, null=True)),
                ('object', models.CharField(max_length=128, null=True)),
                ('dest', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
