# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-27 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ro',
            options={'ordering': ['-created_on'], 'permissions': (('view_video', 'Can view video'),)},
        ),
        migrations.AddField(
            model_name='ro',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ro',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ro',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
