# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180627_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='ro',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
