# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20181106_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='ro',
            name='advertiser',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ro',
            name='brand',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
