# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20190521_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='ro',
            name='ronumber',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
