version: '2'

services:

    web:
      restart: always
      build:
        context: ./web
      depends_on:
        - web_ffmpeg
        - postgres
        - redis
        - rabbitmq
      expose:
        - "8000"
      environment:
        - DEBUG=True
      command: /usr/local/bin/gunicorn wsgi:application -w 2 -b :8000
      logging:
        driver: none
        options:
          syslog-address: "udp://$IP_LOGSTASH:5000"

    web_ffmpeg:
      restart: always
      build:
        context: ./web
      depends_on:
        - postgres
        - redis
        - rabbitmq
      expose:
        - "8000"
      command: /usr/local/bin/celery -A trigger worker -l info
      logging:
        driver: none
        options:
          syslog-address: "udp://$IP_LOGSTASH:5000"


    nginx:
      restart: always
      build:
        context: ./nginx/
      ports:
        - "80:80"
        - "443:443"
      volumes_from:
        - web
      logging:
        driver: none
        options:
          syslog-address: "udp://$IP_LOGSTASH:5000"


    postgres:
      restart: always
      image: postgres:latest
      expose:
        - "5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/
      logging:
        driver: none
        options:
          syslog-address: "udp://$IP_LOGSTASH:5000"

    redis:
      restart: always
      image: redis:latest
      expose:
        - "6379"
      volumes:
        - redisdata:/data
      logging:
        driver: none
        options:
          syslog-address: "udp://$IP_LOGSTASH:5000"


    rabbitmq:
      restart: always
      image: rabbitmq:3-management
      environment:
        RABBITMQ_DEFAULT_USER: 'adminuser'
        RABBITMQ_DEFAULT_PASS: '81#b*Ai272kg'
        RABBITMQ_DEFAULT_VHOST: 'myvhost'
      ports:
        - "15672:15672"
      expose:
        - "5672"
      logging:
        driver: none
        options:
          syslog-address: "udp://$IP_LOGSTASH:5000"


volumes:
    elk-data:
    pgdata:
    redisdata:
    web-data:
    web-ffmpeg-data:
