# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-06 08:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0012_auto_20170505_0351'),
        ('content', '0002_auto_20170329_0730'),
        ('frames', '0002_facerect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('azureFaceId', models.CharField(max_length=128)),
                ('faceImg', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='FaceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Person')),
            ],
        ),
        migrations.CreateModel(
            name='HardCuts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cuts', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
        ),
        migrations.AddField(
            model_name='face',
            name='faceGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contextual.FaceGroup'),
        ),
        migrations.AddField(
            model_name='face',
            name='faceRect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frames.FaceRect'),
        ),
    ]
