# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-06 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contextual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='faceGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contextual.FaceGroup'),
        ),
        migrations.AlterField(
            model_name='face',
            name='faceImg',
            field=models.URLField(verbose_name='Image'),
        ),
    ]
