# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contextual', '0002_auto_20170506_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facegroup',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Person'),
        ),
    ]
