# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20170505_0351'),
        ('contextual', '0004_auto_20170508_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='facegroup',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
