# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-14 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0004_videoframes_time'),
        ('video', '0012_auto_20170505_0351'),
        ('contextual', '0005_facegroup_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFaceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='face',
            old_name='azureFaceId',
            new_name='azure_face_id',
        ),
        migrations.RenameField(
            model_name='face',
            old_name='faceGroup',
            new_name='face_group',
        ),
        migrations.RenameField(
            model_name='face',
            old_name='faceImg',
            new_name='face_img_url',
        ),
        migrations.RemoveField(
            model_name='face',
            name='faceRect',
        ),
        migrations.RemoveField(
            model_name='facegroup',
            name='video',
        ),
        migrations.AddField(
            model_name='face',
            name='face_rect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frames.Rect', verbose_name='Rect'),
        ),
        migrations.AddField(
            model_name='videofacegroup',
            name='face_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contextual.FaceGroup'),
        ),
        migrations.AddField(
            model_name='videofacegroup',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
        migrations.AddField(
            model_name='picturegroup',
            name='face_groups',
            field=models.ManyToManyField(to='contextual.FaceGroup'),
        ),
    ]
