# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_audio_subtitle_transcription'),
        ('contextual', '0008_auto_20170514_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='facegroup',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
