# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 16:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextual', '0009_facegroup_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='facegroup',
            name='timeline',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
