# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextual', '0010_facegroup_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
