# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20180618_1711'),
        ('contextual', '0011_face_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='facegroup',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Character'),
        ),
    ]
