# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-16 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextual', '0012_facegroup_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='emotion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
