# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-12-17 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextual', '0013_face_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardcuts',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hardcuts',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
