# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-12-17 11:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextual', '0014_auto_20191217_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardcuts',
            name='cuts',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None),
        ),
    ]
