# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-07 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contextual', '0016_hardcuts_fcuts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardcuts',
            name='fcuts',
        ),
    ]
