# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-18 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextual', '0017_remove_hardcuts_fcuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='face',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='facegroup',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facegroup',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
