# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-01 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frametag',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='frametag',
            name='time_out',
        ),
    ]
