# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tag_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrameTagCategory',
        ),
    ]
