# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_video_duration'),
        ('content', '0002_auto_20170329_0730'),
        ('tags', '0006_auto_20170116_1010'), # web/tags/migrations/0007_auto_20170329_0730.py
    ]

    operations = [
        migrations.AddField(
            model_name='frametag',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]

