# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_video_duration'),
        ('content', '0002_auto_20170329_0730'),
        ('tags', '0007_auto_20170329_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_in', models.PositiveIntegerField()),
                ('frame_out', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('characters', models.ManyToManyField(related_name='scenes', to='content.Character')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='video.Video')),
                ('tags', models.ManyToManyField(related_name='scenes', to='tags.Tag')),
            ],
        ),
    ]
