# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-05 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_scene_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenetag',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='content.Episode'),
        ),
    ]
