# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_audio_subtitle_transcription'),
        ('tags', '0009_auto_20170505_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_in', models.PositiveIntegerField()),
                ('frame_out', models.PositiveIntegerField()),
                ('words', models.TextField(default='Nothing')),
                ('comment', models.TextField(null=True)),
                ('tags', models.ManyToManyField(related_name='keywords', to='tags.Tag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='video.Video')),
            ],
            options={
                'permissions': (('view_keywordtag', 'Can view keyword tags'),),
            },
        ),
    ]
