# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0010_keywordtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordtag',
            name='sentiment_magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordtag',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
