# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-08 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_videosubtitle'),
        ('tags', '0011_auto_20180304_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_in', models.PositiveIntegerField()),
                ('frame_out', models.PositiveIntegerField()),
                ('words', models.TextField(default='Nothing')),
                ('comment', models.TextField(null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_magnitude', models.FloatField(blank=True, null=True)),
                ('tags', models.ManyToManyField(related_name='ocrtags', to='tags.Tag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocrtags', to='video.Video')),
            ],
            options={
                'permissions': (('view_ocrtag', 'Can view ocr tags'),),
            },
        ),
    ]
