# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.unique_filename
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_auto_20180318_2025'),
        ('tags', '0012_ocrtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tags.Tag')),
                ('poster', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=utils.unique_filename.unique_upload, verbose_name='Poster')),
            ],
            options={
                'permissions': (('view_logo', 'Can view logo'),),
            },
            bases=('tags.tag',),
        ),
        migrations.CreateModel(
            name='LogoTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_in', models.PositiveIntegerField()),
                ('frame_out', models.PositiveIntegerField()),
                ('comment', models.TextField(null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logotag', to='tags.Logo')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logotag', to='video.Video')),
            ],
            options={
                'permissions': (('view_logotag', 'Can view logo tags'),),
            },
        ),
    ]
