# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0014_logo_poster_ppoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtag',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'French'), ('en', 'English'), ('pa', 'Punjabi'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('mr', 'Marathi'), ('ml', 'Malayalam'), ('bn', 'Bengali')], default='en', max_length=2, null=True),
        ),
    ]
