# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-07 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0017_frametag_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='frametag',
            name='is_approved',
            field=models.CharField(blank=True, choices=[('RIV', 'Review'), ('CLN', 'Clean'), ('ACP', 'Accepted'), ('NCP', 'Not Accepted'), ('CHK', 'Check')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='keywordtag',
            name='is_approved',
            field=models.CharField(blank=True, choices=[('RIV', 'Review'), ('CLN', 'Clean'), ('ACP', 'Accepted'), ('NCP', 'Not Accepted'), ('CHK', 'Check')], max_length=3, null=True),
        ),
    ]
