# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_video_created_by'),
        ('tags', '0019_emotiontag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStatusTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved', models.CharField(blank=True, choices=[('RIV', 'Review'), ('CLN', 'Clean'), ('ACP', 'Accepted'), ('NCP', 'Not Accepted'), ('CHK', 'Check')], max_length=3, null=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
            options={
                'permissions': (('view_compliancestatustag', 'Can view compliance status tag'),),
            },
        ),
    ]
