# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-13 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0020_compliancestatustag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancestatustag',
            name='is_approved',
            field=models.CharField(blank=True, choices=[('RIV', 'Review'), ('CLN', 'Clean'), ('ACP', 'Accepted'), ('NCP', 'Not Accepted'), ('CHK', 'Check'), ('CMP', 'Completed')], max_length=3, null=True),
        ),
    ]
