# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-07 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.unique_filename
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_video_created_by'),
        ('tags', '0021_auto_20181013_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_in', models.PositiveIntegerField()),
                ('frame_out', models.PositiveIntegerField()),
                ('comment', models.TextField(null=True)),
                ('words', models.TextField(null=True)),
                ('is_approved', models.CharField(blank=True, choices=[('RIV', 'Review'), ('CLN', 'Clean'), ('ACP', 'Accepted'), ('NCP', 'Not Accepted'), ('CHK', 'Check')], max_length=3, null=True)),
                ('poster', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=utils.unique_filename.unique_upload, verbose_name='Poster')),
                ('poster_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('content_language_code', models.IntegerField(blank=True, default=0, null=True)),
                ('telecast_start_time', models.TimeField()),
                ('telecast_end_time', models.TimeField()),
                ('telecast_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('promo_sponsor_name', models.CharField(max_length=512)),
                ('is_original', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barctag', to='tags.Tag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barctag', to='video.Video')),
            ],
            options={
                'permissions': (('view_barctag', 'Can view barc tag'),),
            },
        ),
    ]
