# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-09 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0024_remove_barctag_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barctag',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barctag',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barctag', to='tags.Tag'),
        ),
    ]
