# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-09 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0025_auto_20181209_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barctag',
            name='is_approved',
            field=models.CharField(blank=True, choices=[('RIV', 'Review'), ('CLN', 'Clean'), ('ACP', 'Accepted'), ('NCP', 'Not Accepted'), ('CHK', 'Check')], default='CLN', max_length=3, null=True),
        ),
    ]
