# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-10 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0028_auto_20181210_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='barctag',
            name='brand_sector',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
