# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-22 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_video_created_by'),
        ('tags', '0029_barctag_brand_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpriteTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.IntegerField(blank=True, default=0)),
                ('url', models.URLField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
        ),
    ]
