# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0031_auto_20181227_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptor',
            name='text',
            field=models.CharField(max_length=128),
        ),
    ]
