# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-28 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0032_auto_20181227_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasted_promo', to='tags.Channel'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_promo', to='tags.Channel'),
        ),
    ]
