# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-28 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0034_auto_20181228_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Title'),
        ),
    ]
