# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-28 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0036_trigram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playouttag',
            name='telecast_duration',
        ),
        migrations.RemoveField(
            model_name='playouttag',
            name='telecast_end_time',
        ),
        migrations.RemoveField(
            model_name='playouttag',
            name='telecast_start_time',
        ),
    ]
