# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-28 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0037_auto_20181228_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordtag',
            name='word_level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
