# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-21 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0039_playouttag_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.URLField(blank=True, null=True)),
                ('content_language', models.CharField(blank=True, max_length=64, null=True)),
                ('telecast_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('advertiser_group', models.CharField(blank=True, max_length=128, null=True)),
                ('advertiser', models.CharField(blank=True, max_length=128, null=True)),
                ('brand_title', models.CharField(blank=True, max_length=128, null=True)),
                ('brand_category', models.CharField(blank=True, max_length=128, null=True)),
                ('brand_sector', models.CharField(blank=True, max_length=128, null=True)),
                ('descriptor', models.CharField(blank=True, max_length=512, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'permissions': (('view_commercialtag', 'Can view commercial tag'),),
            },
        ),
    ]
