# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0046_auto_20190311_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
