# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-12 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0047_auto_20190311_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptor',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
