# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-01 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0051_auto_20190601_0854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commercial',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set([]),
        ),
    ]
