# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-01 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0052_auto_20190601_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='descriptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Descriptor'),
        ),
    ]
