# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0053_auto_20190601_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playouttag',
            name='content_type',
            field=models.CharField(blank=True, choices=[('promo', 'Promo'), ('commercial', 'Commercial'), ('program', 'Program'), ('song', 'Song')], max_length=128, null=True),
        ),
    ]
