# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0054_auto_20190620_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancestatustag',
            name='is_approved',
            field=models.CharField(blank=True, choices=[('RIV', 'Review'), ('CLN', 'Clean'), ('ACP', 'Accepted'), ('NCP', 'Not Accepted'), ('CHK', 'Check'), ('CMP', 'Completed'), ('RPT', 'Report Sent'), ('WIP', 'In Progress')], max_length=3, null=True),
        ),
    ]
