# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-24 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0055_auto_20190623_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commercial',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promo',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
