# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0057_frametag_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='frametag',
            name='is_cbfc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='keywordtag',
            name='is_cbfc',
            field=models.BooleanField(default=False),
        ),
    ]
