# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-13 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0058_auto_20190702_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programgenre',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
