# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-16 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0059_auto_20190713_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlanguage',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programtheme',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
