# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-18 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0060_auto_20190716_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
