# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0061_commercial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Title'),
        ),
    ]
