# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-21 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0063_auto_20190721_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocategory',
            name='code',
            field=models.IntegerField(blank=True, default=403091393, null=True),
        ),
    ]
