# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import tags.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0065_auto_20190721_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.random_code),
        ),
        migrations.AlterField(
            model_name='advertisergroup',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.random_code),
        ),
        migrations.AlterField(
            model_name='brandcategory',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.random_code),
        ),
        migrations.AlterField(
            model_name='brandname',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.random_code),
        ),
        migrations.AlterField(
            model_name='brandsector',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.random_code),
        ),
        migrations.AlterField(
            model_name='descriptor',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.random_code),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.random_code),
        ),
        migrations.AlterField(
            model_name='promotype',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.random_code),
        ),
        migrations.AlterField(
            model_name='title',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.random_code),
        ),
    ]
