# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-21 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import tags.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0066_auto_20190721_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelgenre',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_channelgenre_code),
        ),
        migrations.AlterField(
            model_name='channelnetwork',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_network_code),
        ),
        migrations.AlterField(
            model_name='contentlanguage',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_lang_code),
        ),
        migrations.AlterField(
            model_name='programgenre',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_programgenre_code),
        ),
        migrations.AlterField(
            model_name='programtheme',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_programtheme_code),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_region_code),
        ),
    ]
