# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-27 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import tags.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0070_auto_20190725_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_ad_code),
        ),
        migrations.AlterField(
            model_name='advertisergroup',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_adgroup_code),
        ),
        migrations.AlterField(
            model_name='brandcategory',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_cat_code),
        ),
        migrations.AlterField(
            model_name='brandsector',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_sector_code),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_prod_code),
        ),
    ]
