# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-27 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import tags.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0071_auto_20190727_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandname',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_brandname_code),
        ),
        migrations.AlterField(
            model_name='descriptor',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_descriptor_code),
        ),
        migrations.AlterField(
            model_name='promocategory',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_promocat_code),
        ),
        migrations.AlterField(
            model_name='promotype',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_promotype_code),
        ),
        migrations.AlterField(
            model_name='title',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_title_code),
        ),
    ]
