# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-19 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0072_auto_20190727_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentlanguage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentlanguage',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programgenre',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programgenre',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocategory',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocategory',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
