# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-21 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import tags.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0073_auto_20190819_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelgenre',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_channelgenre_code),
        ),
        migrations.AlterField(
            model_name='channelnetwork',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_network_code),
        ),
        migrations.AlterField(
            model_name='contentlanguage',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_lang_code),
        ),
        migrations.AlterField(
            model_name='programgenre',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_programgenre_code),
        ),
        migrations.AlterField(
            model_name='programtheme',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_programtheme_code),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_region_code),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_ad_code),
        ),
        migrations.AlterField(
            model_name='advertisergroup',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_adgroup_code),
        ),
        migrations.AlterField(
            model_name='brandcategory',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_cat_code),
        ),
        migrations.AlterField(
            model_name='brandsector',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_sector_code),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_prod_code),
        ),
        migrations.AlterField(
            model_name='brandname',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_brandname_code),
        ),
        migrations.AlterField(
            model_name='descriptor',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_descriptor_code),
        ),
        migrations.AlterField(
            model_name='promocategory',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_promocat_code),
        ),
        migrations.AlterField(
            model_name='promotype',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_promotype_code),
        ),
        migrations.AlterField(
            model_name='title',
            name='code',
            field=models.IntegerField(blank=True, default=tags.models.auto_title_code),
        ),
    ]