# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-03 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import tags.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0074_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='code',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentlanguage',
            name='code',
            field=models.IntegerField(blank=True, db_index=True, default=tags.models.auto_lang_code),
        ),
    ]
