# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-16 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0075_auto_20190903_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playouttag',
            name='object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='playouttag',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
