# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-17 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0076_auto_20190916_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='playouttag',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
