# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-15 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0077_playouttag_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frametag',
            name='tag',
        ),
        migrations.AddField(
            model_name='frametag',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='frametag', to='tags.Tag'),
        ),
    ]
