# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-24 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0080_generictag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frametag',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='frametag', to='tags.GenericTag'),
        ),
    ]
