# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-27 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_auto_20191227_0741'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0082_auto_20191224_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_in', models.PositiveIntegerField()),
                ('frame_out', models.PositiveIntegerField()),
                ('comment', models.TextField(null=True)),
                ('words', models.TextField(null=True)),
                ('is_approved', models.CharField(blank=True, choices=[('RIV', 'Review'), ('CLN', 'Clean'), ('ACP', 'Accepted'), ('NCP', 'Not Accepted'), ('CHK', 'Check')], max_length=3, null=True)),
                ('is_cbfc', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(null=True, related_name='frametag', to='tags.GenericTag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='video.Video')),
            ],
            options={
                'permissions': (('view_frametag', 'Can view frame tags'),),
            },
        ),
        migrations.RemoveField(
            model_name='frametag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='frametag',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='frametag',
            name='is_cbfc',
        ),
        migrations.RemoveField(
            model_name='frametag',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='frametag',
            name='tags',
        ),
        migrations.AddField(
            model_name='frametag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frametag', to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='frametag',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frametag', to='video.Video'),
        ),
    ]
