# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-12-31 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0083_auto_20191227_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtag',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='frametag', to='tags.GenericTag'),
        ),
    ]
