# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-06 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0084_auto_20191231_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtag',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manualtag', to='video.Video'),
        ),
    ]
