# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-08 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0085_auto_20200106_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='frametag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frametag',
            name='is_cbfc',
            field=models.BooleanField(default=False),
        ),
    ]
