# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-22 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0087_manualtag_qc_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTagQCStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qc_approved', models.BooleanField(default=True)),
            ],
            options={
                'permissions': (('view_manualtagqcstatus', 'Can view manualtagqcstatus'),),
            },
        ),
        migrations.RemoveField(
            model_name='manualtag',
            name='qc_approved',
        ),
        migrations.AddField(
            model_name='manualtagqcstatus',
            name='manual_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.ManualTag'),
        ),
        migrations.AddField(
            model_name='manualtagqcstatus',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.GenericTag'),
        ),
        migrations.AlterUniqueTogether(
            name='manualtagqcstatus',
            unique_together=set([('tag', 'manual_tag')]),
        ),
    ]
