# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0088_auto_20200122_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frametag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frametag', to='tags.GenericTag'),
        ),
        migrations.AlterField(
            model_name='manualtag',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='manualtag', to='tags.GenericTag'),
        ),
    ]
