# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-20 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0089_auto_20200220_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frametag',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frametag', to='tags.GenericTag'),
        ),
    ]
