# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-03 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0090_auto_20200220_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordtag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
