# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-03 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0091_keywordtag_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordtag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
