# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-15 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0092_auto_20200303_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterReportGen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('RDY', 'Ready'), ('NRY', 'Not Ready'), ('PRG', 'In Progress')], default='NRY', max_length=4)),
                ('file', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
