# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-20 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0093_masterreportgen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frametag',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='keywordtag',
            name='is_approved',
        ),
    ]
