# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-23 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0135_assetversion_active'),
        ('tags', '0095_auto_20200420_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='frametag',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Collection'),
        ),
        migrations.AddField(
            model_name='frametag',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
