# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0096_auto_20200423_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterreportgen',
            name='status',
            field=models.CharField(choices=[('RDY', 'Ready'), ('NRY', 'Not Ready'), ('PRG', 'In Progress'), ('FAI', 'Fail')], default='NRY', max_length=4),
        ),
    ]
