# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-25 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0098_auto_20200515_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionhouse',
            name='name',
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
