# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-06-05 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0099_auto_20200525_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='frametag',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='frametag',
            name='up_left_x',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='frametag',
            name='up_left_y',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='frametag',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
