# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-06-08 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0100_auto_20210605_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='frametag',
            name='img_height',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='frametag',
            name='img_width',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='frametag',
            name='height',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='frametag',
            name='up_left_x',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='frametag',
            name='up_left_y',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='frametag',
            name='width',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
