# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-06-16 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0068_video_picture'),
        ('tags', '0102_checktag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_in', models.PositiveIntegerField()),
                ('frame_out', models.PositiveIntegerField()),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='checktag',
            name='frame_in',
        ),
        migrations.RemoveField(
            model_name='checktag',
            name='frame_out',
        ),
        migrations.RemoveField(
            model_name='checktag',
            name='image_url',
        ),
        migrations.AddField(
            model_name='correctiontag',
            name='checktag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='tags.CheckTag'),
        ),
        migrations.AddField(
            model_name='correctiontag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctiontag',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correctiontag', to='video.Video'),
        ),
    ]
