# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-02-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0104_auto_20210628_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.TextField(null=True)),
                ('color', models.TextField(null=True)),
                ('radius', models.FloatField(blank=True, default=0)),
                ('startx', models.FloatField(blank=True, default=0)),
                ('starty', models.FloatField(blank=True, default=0)),
                ('last_mousex', models.FloatField(blank=True, default=0)),
                ('last_mousey', models.FloatField(blank=True, default=0)),
                ('width', models.FloatField(blank=True, default=0)),
                ('height', models.FloatField(blank=True, default=0)),
                ('mousex', models.FloatField(blank=True, default=0)),
                ('mousey', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='frametag',
            name='is_edl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frametag',
            name='is_india',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frametag',
            name='is_international',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frametag',
            name='markers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frametag', to='tags.Marker'),
        ),
    ]
