# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-03-07 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0105_auto_20220218_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frametag',
            name='markers',
        ),
        migrations.AddField(
            model_name='marker',
            name='markers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.FrameTag'),
        ),
    ]
