# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-03-17 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0106_auto_20220307_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='markers',
            new_name='frame_tag',
        ),
    ]
