# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161201_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user', 'Can view user'),)},
        ),
    ]
