# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validator
import utils.unique_filename
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170118_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.FileField(upload_to=utils.unique_filename.unique_upload, validators=[users.validator.validate_img_file_type])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('Address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
