# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170706_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('view_profile', 'Can view profile'),)},
        ),
    ]
