# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-14 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publised_date', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'permissions': (('view_publication', 'Can view publication'),),
            },
        ),
    ]
