# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-14 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publised_date',
        ),
    ]
