# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-01 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import utils.unique_filename
import uuid
import versatileimagefield.fields
import video.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=utils.unique_filename.unique_upload, validators=[video.validator.validate_video_file_type])),
                ('is_removed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('poster', versatileimagefield.fields.VersatileImageField(null=True, upload_to=utils.unique_filename.unique_upload, verbose_name='Poster')),
                ('poster_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
            options={
                'permissions': (('view_video', 'Can view videos'),),
            },
        ),
    ]
