# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-13 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20170103_0354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='VideoLibrary',
        ),
    ]
