# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-19 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20170113_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
