# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20170119_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='total_frames',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_codec',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.AlterField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
