# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-05 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20170404_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.URLField(),
        ),
    ]
