# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_videosubtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_on'], 'permissions': (('view_video', 'Can view video'),)},
        ),
    ]
