# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-28 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0066_assetversion'),
        ('video', '0016_video_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.AssetVersion'),
        ),
    ]
