# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-27 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_subtitle_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='version',
            new_name='asset_version',
        ),
    ]
