# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-08 12:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_auto_20191227_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProxyPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='Name')),
                ('nbm', models.CharField(blank=True, max_length=1024, null=True)),
                ('source', models.CharField(blank=True, max_length=1024, null=True)),
                ('master', models.CharField(blank=True, max_length=1024, null=True)),
                ('intermediate', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, null=True, size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
