# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-09 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_videoproxypath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoproxypath',
            old_name='source',
            new_name='file',
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='nbm_processing_status',
            field=models.CharField(blank=True, choices=[('QUE', 'Queued'), ('PRD', 'Procesed'), ('PRO', 'Processing')], default='QUE', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='nbm_progress',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='nbm_storage_status',
            field=models.CharField(blank=True, choices=[('NPR', 'Not Processed'), ('ONL', 'Online'), ('ARC', 'Archived')], default='NPR', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='sourceproxy',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='sourceproxy_processing_status',
            field=models.CharField(blank=True, choices=[('QUE', 'Queued'), ('PRD', 'Procesed'), ('PRO', 'Processing')], default='QUE', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='sourceproxy_progress',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='videoproxypath',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Name'),
        ),
    ]
