# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-20 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0024_auto_20200116_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bitrate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
