# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-20 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0025_auto_20200120_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='size',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
