# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0026_auto_20200120_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproxypath',
            name='sourceproxy_upload_progress',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='sourceproxy_upload_status',
            field=models.CharField(blank=True, choices=[('UPD', 'Sucessfully Uploaded'), ('FAI', 'Uploading Failed'), ('NST', 'Uploading not Started'), ('UPL', 'Uploading')], default='NST', max_length=3, null=True),
        ),
    ]
