# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-22 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0028_auto_20200121_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproxypath',
            name='sourceproxy_upload_status',
            field=models.CharField(blank=True, choices=[('NST', 'Uploading not Started'), ('UPD', 'Sucessfully Uploaded'), ('FAI', 'Uploading Failed'), ('UPL', 'Uploading')], default='NST', max_length=3, null=True),
        ),
    ]
