# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0039_auto_20200205_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproxypath',
            name='sourceproxy_upload_status',
            field=models.CharField(blank=True, choices=[('FAI', 'Uploading Failed'), ('UPD', 'Sucessfully Uploaded'), ('UPL', 'Uploading'), ('NST', 'Uploading not Started')], default='NST', max_length=3, null=True),
        ),
    ]
