# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-05 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0040_auto_20200205_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT STARTED', 'Queued'), ('SUCCESS', 'Success'), ('EXISITS', 'Processing'), ('FAILED', 'Failed')], default='NOT STARTED', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('PREPARING', 'Preparing'), ('WAIT FOR JOB', 'Queued'), ('PROCESSING', 'Processing'), ('PROCESSED ', 'Processed'), ('DONE', 'Done')], default='PREPARING', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='videoproxypath',
            name='sourceproxy_upload_status',
            field=models.CharField(blank=True, choices=[('FAI', 'Uploading Failed'), ('UPL', 'Uploading'), ('NST', 'Uploading not Started'), ('UPD', 'Sucessfully Uploaded')], default='NST', max_length=3, null=True),
        ),
    ]
