# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-18 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0110_auto_20200208_1227'),
        ('video', '0044_auto_20200208_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproxypath',
            name='asset_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.AssetVersion'),
        ),
        migrations.AlterField(
            model_name='videoproxypath',
            name='sourceproxy_upload_status',
            field=models.CharField(blank=True, choices=[('FAI', 'Uploading Failed'), ('UPL', 'Uploading'), ('UPD', 'Sucessfully Uploaded'), ('NST', 'Uploading not Started')], default='NST', max_length=3, null=True),
        ),
    ]
