# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-18 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0050_auto_20200218_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.VideoProxyPath'),
        ),
        migrations.AlterField(
            model_name='videoproxypath',
            name='sourceproxy_upload_status',
            field=models.CharField(blank=True, choices=[('NST', 'Uploading not Started'), ('UPL', 'Uploading'), ('FAI', 'Uploading Failed'), ('UPD', 'Sucessfully Uploaded')], default='NST', max_length=3, null=True),
        ),
    ]
