# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-19 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0052_auto_20200219_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproxypath',
            name='sourceproxy_upload_status',
            field=models.CharField(blank=True, choices=[('UPL', 'Uploading'), ('FAI', 'Uploading Failed'), ('NST', 'Uploading not Started'), ('UPD', 'Sucessfully Uploaded')], default='NST', max_length=3, null=True),
        ),
    ]
