# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0053_auto_20200219_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproxypath',
            name='sourceproxy_upload_status',
            field=models.CharField(blank=True, choices=[('UPD', 'Sucessfully Uploaded'), ('FAI', 'Uploading Failed'), ('NST', 'Uploading not Started'), ('UPL', 'Uploading')], default='NST', max_length=3, null=True),
        ),
    ]
