# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-02 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0056_auto_20200224_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoproxypath',
            name='sourceproxy_upload_status',
            field=models.CharField(blank=True, choices=[('NST', 'Uploading not Started'), ('FAI', 'Uploading Failed'), ('UPL', 'Uploading'), ('UPD', 'Sucessfully Uploaded')], default='NST', max_length=3, null=True),
        ),
    ]
