# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-03 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0058_auto_20200302_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT STARTED', 'Queued'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('EXISITS', 'Archived'), ('FAILED', 'Failed')], default='NOT STARTED', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='videoproxypath',
            name='sourceproxy_upload_status',
            field=models.CharField(blank=True, choices=[('UPL', 'Uploading'), ('FAI', 'Uploading Failed'), ('UPD', 'Sucessfully Uploaded'), ('NST', 'Uploading not Started')], default='NST', max_length=3, null=True),
        ),
    ]
