# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-25 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0062_auto_20200306_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproxypath',
            name='nbm_storage_status',
            field=models.CharField(blank=True, choices=[('NPR', 'Not Processed'), ('ONL', 'Online'), ('ARC', 'Archived'), ('ALL', 'Online & Archived')], default='NPR', max_length=3, null=True),
        ),
    ]
