# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-29 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0063_auto_20200425_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproxypath',
            name='ingest_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
