# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-01 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0064_videoproxypath_ingest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproxypath',
            name='audio_bitrate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='audio_codec',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='audio_sample_rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='audio_tracks_no',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='bitrate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='frame_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='size',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='total_frames',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='video_codec',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='videoproxypath',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
