# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-01 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0066_auto_20200501_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproxypath',
            name='ingest_date',
        ),
    ]
