# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-12 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0067_remove_videoproxypath_ingest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
