# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-04-12 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0069_auto_20210618_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_nft',
            field=models.BooleanField(default=False),
        ),
    ]
