# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-26 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0059_channelclip_filled_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.URLField()),
                ('date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Channel')),
            ],
            options={
                'permissions': (('view_masterreport', 'Can view master report'),),
            },
        ),
        migrations.CreateModel(
            name='SuperMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.URLField()),
                ('date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'permissions': (('view_masterreport', 'Can view master report'),),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'permissions': (('view_vendor', 'Can view vendor'),),
            },
        ),
        migrations.CreateModel(
            name='VendorMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.URLField()),
                ('date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Vendor')),
            ],
            options={
                'permissions': (('view_vendormaster', 'Can view vendor master'),),
            },
        ),
        migrations.CreateModel(
            name='VendorReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.URLField()),
                ('date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Channel')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Vendor')),
            ],
            options={
                'permissions': (('view_vendorreport', 'Can view vendor report'),),
            },
        ),
    ]
