# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-26 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterreport',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Channel'),
        ),
        migrations.AlterField(
            model_name='vendorreport',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Channel'),
        ),
    ]
