# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0050_auto_20190313_1411'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0002_auto_20190426_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCommercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('title_code', models.CharField(max_length=128)),
                ('brand_name', models.CharField(max_length=128)),
                ('brand_name_code', models.CharField(max_length=128)),
                ('brand_sector', models.CharField(max_length=128)),
                ('brand_sector_code', models.CharField(max_length=128)),
                ('brand_category', models.CharField(max_length=128)),
                ('brand_category_code', models.CharField(max_length=128)),
                ('advertiser', models.CharField(max_length=128)),
                ('advertiser_code', models.CharField(max_length=128)),
                ('advertiser_group', models.CharField(max_length=128)),
                ('advertiser_group_code', models.CharField(max_length=128)),
                ('descriptor', models.CharField(max_length=128)),
                ('descriptor_code', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('title_code', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=128)),
                ('language_code', models.CharField(max_length=128)),
                ('prod_house', models.CharField(max_length=128)),
                ('prod_house_code', models.CharField(max_length=128)),
                ('program_genre', models.CharField(max_length=128)),
                ('program_genre_code', models.CharField(max_length=128)),
                ('program_theme', models.CharField(max_length=128)),
                ('program_theme_code', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Channel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPromo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('title_code', models.CharField(max_length=128)),
                ('brand_name', models.CharField(max_length=128)),
                ('brand_name_code', models.CharField(max_length=128)),
                ('brand_sector', models.CharField(max_length=128)),
                ('brand_sector_code', models.CharField(max_length=128)),
                ('brand_category', models.CharField(max_length=128)),
                ('brand_category_code', models.CharField(max_length=128)),
                ('advertiser', models.CharField(max_length=128)),
                ('advertiser_code', models.CharField(max_length=128)),
                ('advertiser_group', models.CharField(max_length=128)),
                ('advertiser_group_code', models.CharField(max_length=128)),
                ('descriptor', models.CharField(max_length=128)),
                ('descriptor_code', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Vendor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vendorpromo',
            unique_together=set([('brand_name', 'descriptor', 'vendor')]),
        ),
        migrations.AlterUniqueTogether(
            name='vendorprogram',
            unique_together=set([('title', 'channel', 'vendor')]),
        ),
        migrations.AlterUniqueTogether(
            name='vendorcommercial',
            unique_together=set([('brand_name', 'descriptor', 'vendor')]),
        ),
    ]
