# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20190430_0226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorcommercial',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='vendorprogram',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='vendorpromo',
            unique_together=set([]),
        ),
    ]
