# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-01 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0050_auto_20190313_1411'),
        ('masters', '0004_auto_20190430_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='vendorcommercial',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorcommercial',
            name='super_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Commercial'),
        ),
        migrations.AddField(
            model_name='vendorprogram',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprogram',
            name='super_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Program'),
        ),
        migrations.AddField(
            model_name='vendorpromo',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorpromo',
            name='super_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Promo'),
        ),
    ]
