# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_auto_20190501_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpromo',
            name='advertiser',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='advertiser_group',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='descriptor',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
