# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_auto_20190506_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprogram',
            name='language',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='language_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='prod_house',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='prod_house_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='program_genre',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='program_genre_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='program_theme',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='program_theme_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='title_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='advertiser_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='advertiser_group_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='descriptor_code',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
