# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_auto_20190506_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprogram',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Channel'),
        ),
    ]
