# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 08:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_supercommercial_superprogram_superpromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcommercial',
            name='durations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), null=True, size=12),
        ),
    ]
