# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_auto_20190507_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterreport',
            name='eta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterreport',
            name='status',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
