# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_auto_20190507_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterreport',
            name='status',
            field=models.CharField(default='NPR', max_length=128, null=True),
        ),
    ]
