# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 04:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_auto_20190507_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='advertiser_group',
        ),
        migrations.RemoveField(
            model_name='brandcategory',
            name='brand_sector',
        ),
        migrations.RemoveField(
            model_name='brandname',
            name='brand_category',
        ),
        migrations.RemoveField(
            model_name='programgenre',
            name='program_theme',
        ),
        migrations.DeleteModel(
            name='PromoCategory',
        ),
        migrations.DeleteModel(
            name='PromoType',
        ),
        migrations.RemoveField(
            model_name='supercommercial',
            name='advertiser',
        ),
        migrations.RemoveField(
            model_name='supercommercial',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='supercommercial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supercommercial',
            name='descriptor',
        ),
        migrations.RemoveField(
            model_name='supercommercial',
            name='title',
        ),
        migrations.RemoveField(
            model_name='superprogram',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='superprogram',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='superprogram',
            name='language',
        ),
        migrations.RemoveField(
            model_name='superprogram',
            name='prod_house',
        ),
        migrations.RemoveField(
            model_name='superprogram',
            name='program_genre',
        ),
        migrations.RemoveField(
            model_name='superprogram',
            name='title',
        ),
        migrations.RemoveField(
            model_name='superpromo',
            name='advertiser',
        ),
        migrations.RemoveField(
            model_name='superpromo',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='superpromo',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='superpromo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='superpromo',
            name='descriptor',
        ),
        migrations.RemoveField(
            model_name='superpromo',
            name='promo_channel',
        ),
        migrations.RemoveField(
            model_name='superpromo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='vendorcommercial',
            name='super_commercial',
        ),
        migrations.RemoveField(
            model_name='vendorprogram',
            name='super_program',
        ),
        migrations.RemoveField(
            model_name='vendorpromo',
            name='super_promo',
        ),
        migrations.AlterField(
            model_name='vendorcommercial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Advertiser',
        ),
        migrations.DeleteModel(
            name='AdvertiserGroup',
        ),
        migrations.DeleteModel(
            name='BrandCategory',
        ),
        migrations.DeleteModel(
            name='BrandName',
        ),
        migrations.DeleteModel(
            name='BrandSector',
        ),
        migrations.DeleteModel(
            name='ContentLanguage',
        ),
        migrations.DeleteModel(
            name='Descriptor',
        ),
        migrations.DeleteModel(
            name='ProductionHouse',
        ),
        migrations.DeleteModel(
            name='ProgramGenre',
        ),
        migrations.DeleteModel(
            name='ProgramTheme',
        ),
        migrations.DeleteModel(
            name='SuperCommercial',
        ),
        migrations.DeleteModel(
            name='SuperProgram',
        ),
        migrations.DeleteModel(
            name='SuperPromo',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
