# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-10 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_vendormastercomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormastercomparison',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
