# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0019_auto_20190516_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprogram',
            name='program_genre',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='program_theme',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='title',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='title',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
