# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0050_auto_20190313_1411'),
        ('masters', '0022_auto_20190517_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcommercial',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.Commercial'),
        ),
        migrations.AddField(
            model_name='vendorprogram',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.Program'),
        ),
        migrations.AddField(
            model_name='vendorpromo',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.Promo'),
        ),
    ]
