# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-22 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0023_auto_20190520_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcommercial',
            name='descriptor_code',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendorcommercial',
            name='title_code',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='program_genre_code',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='program_theme_code',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='title_code',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='title_code',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
