# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-01 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_auto_20190531_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcommercial',
            name='advertiser',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendorcommercial',
            name='advertiser_group',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendorcommercial',
            name='brand_category',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendorcommercial',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendorcommercial',
            name='brand_sector',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='language',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprogram',
            name='prod_house',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='advertiser',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='advertiser_group',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='brand_category',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='brand_sector',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='descriptor',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
