# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_auto_20190601_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcommercial',
            name='descriptor',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcommercial',
            name='descriptor_code',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
