# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0027_auto_20190602_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('master_file', models.URLField()),
                ('report_file', models.URLField()),
                ('week', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'permissions': (('view_weeklyreport', 'Can view weekly report'),),
            },
        ),
    ]
