# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-20 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0062_auto_20190719_1528'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0028_weeklyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorContentLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('code', models.CharField(db_index=True, max_length=128)),
                ('is_mapped', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('content_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('similars', models.ManyToManyField(blank=True, related_name='_vendorcontentlanguage_similars_+', to='masters.VendorContentLanguage')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProgramGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('code', models.CharField(db_index=True, max_length=128)),
                ('program_theme', models.CharField(db_index=True, max_length=128)),
                ('program_theme_code', models.CharField(db_index=True, max_length=128)),
                ('is_mapped', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('program_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ProgramGenre')),
                ('similars', models.ManyToManyField(blank=True, related_name='_vendorprogramgenre_similars_+', to='masters.VendorProgramGenre')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPromoCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('code', models.CharField(db_index=True, max_length=128)),
                ('is_mapped', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('promo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.PromoCategory')),
                ('similars', models.ManyToManyField(blank=True, related_name='_vendorpromocategory_similars_+', to='masters.VendorPromoCategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.Channel'),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='genre',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='genre_code',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='language',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='language_code',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='network_name',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='network_name_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='region',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='region_code',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendorchannel',
            name='similars',
            field=models.ManyToManyField(blank=True, related_name='_vendorchannel_similars_+', to='masters.VendorChannel'),
        ),
        migrations.AlterField(
            model_name='vendorchannel',
            name='code',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
