# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-11 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_video_created_by'),
        ('masters', '0030_auto_20190726_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcommercial',
            name='video',
            field=models.ManyToManyField(to='video.Video'),
        ),
        migrations.AddField(
            model_name='vendorpromo',
            name='video',
            field=models.ManyToManyField(to='video.Video'),
        ),
    ]
