# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0031_auto_20190811_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormastercomparison',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
