# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_vendormastercomparison_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcommercial',
            name='brand_name_code',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendorpromo',
            name='brand_name_code',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
