# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-23 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0033_auto_20190912_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcommercial',
            name='advertiser',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcommercial',
            name='advertiser_group',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcommercial',
            name='brand_category',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcommercial',
            name='brand_sector',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
