# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import frames.validator
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0006_auto_20170116_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frames',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='', validators=[frames.validator.validate_img_file_type])),
            ],
        ),
        migrations.CreateModel(
            name='Rect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rects', to='frames.Frames')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
