# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-06 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20170505_0351'),
        ('frames', '0002_facerect'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFrames',
            fields=[
                ('frames_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frames.Frames')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
            bases=('frames.frames',),
        ),
        migrations.AlterField(
            model_name='facerect',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_rects', to='frames.VideoFrames'),
        ),
        migrations.AlterField(
            model_name='frames',
            name='file',
            field=models.URLField(),
        ),
    ]
