# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-07 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0003_auto_20170506_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoframes',
            name='time',
            field=models.FloatField(default=0, null=True),
        ),
    ]
