# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-14 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0005_auto_20170514_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frames',
            options={'verbose_name_plural': 'Frames'},
        ),
    ]
