# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import utils.unique_filename


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0006_auto_20170514_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyframe',
            name='file',
            field=models.ImageField(null=True, upload_to=utils.unique_filename.unique_upload),
        ),
    ]
