# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0009_personframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personframe',
            name='frame',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personframes', to='frames.Frames'),
        ),
        migrations.AlterField(
            model_name='personframe',
            name='person',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personframes', to='content.Person'),
        ),
    ]
