# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-30 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True, unique=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workgroup', to='auth.Group')),
            ],
            options={
                'permissions': (('view_workgroup', 'Can view work group'),),
            },
        ),
    ]
