# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-01 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_library'),
        ('workgroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='videolibrary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workgroup', to='video.VideoLibrary'),
        ),
    ]
