# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workgroups', '0005_auto_20170115_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
