# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-25 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('workgroups', '0007_auto_20180910_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('permissions', models.ManyToManyField(blank=True, null=True, to='auth.Permission')),
            ],
            options={
                'permissions': (('view_role', 'Can view role'),),
            },
        ),
    ]
