# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-02 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workgroups', '0008_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workgroups.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workgroups.WorkGroup')),
            ],
            options={
                'permissions': (('view_workgroupmembership', 'Can view work group membership'),),
            },
        ),
    ]
