# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 07:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=128, verbose_name='Name')),
                ('parent_company', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ContextType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_title', models.CharField(max_length=128)),
                ('secondary_title', models.CharField(blank=True, max_length=128)),
                ('short_title', models.CharField(blank=True, max_length=128)),
                ('episode_number', models.PositiveIntegerField()),
                ('telecast_date', models.DateField()),
                ('language', models.TextField(blank=True)),
                ('content_subject', models.CharField(blank=True, max_length=128)),
                ('content_synopsis', models.TextField(blank=True)),
                ('set_in_location', models.CharField(blank=True, max_length=128)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=20)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Channel')),
                ('characters', models.ManyToManyField(to='content.Character')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.ContextType')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('dob', models.DateField()),
                ('born_location', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series_title', models.CharField(max_length=128)),
                ('alternate_title', models.CharField(blank=True, max_length=128)),
                ('short_title', models.CharField(blank=True, max_length=128)),
                ('version', models.CharField(blank=True, max_length=128)),
                ('part', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('year_of_release', models.DateField()),
                ('number_of_episodes', models.PositiveIntegerField()),
                ('genre', models.ManyToManyField(to='content.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='genre',
            field=models.ManyToManyField(to='content.Genre'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Series'),
        ),
        migrations.AddField(
            model_name='character',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Person'),
        ),
        migrations.AddField(
            model_name='character',
            name='tv_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Series'),
        ),
    ]
