# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170329_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('persons', models.ManyToManyField(to='content.Person')),
            ],
        ),
    ]
