# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_persongroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persongroup',
            name='persons',
            field=models.ManyToManyField(blank=True, to='content.Person'),
        ),
    ]
