# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170509_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cloud_id', models.CharField(max_length=128)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Person')),
            ],
        ),
    ]
