# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20170514_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='persongroup',
            name='upload_progress',
            field=models.FloatField(default='0', null=True),
        ),
    ]
