# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import utils.unique_filename
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_persongroup_upload_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('dob', models.DateField(blank=True, null=True)),
                ('born_location', models.CharField(blank=True, max_length=128)),
                ('father_name', models.CharField(blank=True, max_length=128, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('political_party', models.CharField(blank=True, max_length=128, null=True)),
                ('constituency', models.CharField(blank=True, max_length=128, null=True)),
                ('religion', models.CharField(blank=True, max_length=128, null=True)),
                ('caste', models.CharField(blank=True, max_length=128, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('positions', models.TextField(blank=True, max_length=256, null=True)),
                ('picture', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=utils.unique_filename.unique_upload, verbose_name='Poster')),
                ('poster_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
            options={
                'permissions': (('view_politician', 'Can view politician'),),
            },
        ),
    ]
