# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.unique_filename
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_politician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='born_location',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='education',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='name',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='poster_ppoi',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='religion',
        ),
        migrations.AddField(
            model_name='person',
            name='caste',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='current_location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='father_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='mother_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=utils.unique_filename.unique_upload, verbose_name='Poster'),
        ),
        migrations.AddField(
            model_name='person',
            name='poster_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='religion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Person'),
        ),
    ]
