# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='telecast_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(blank=True, to='content.Genre'),
        ),
        migrations.AlterField(
            model_name='series',
            name='number_of_episodes',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='part',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='year_of_release',
            field=models.DateField(blank=True),
        ),
    ]
