# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20180303_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
