# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20180303_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(blank=True, to='content.Genre'),
        ),
    ]
