# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_videosubtitle'),
        ('content', '0019_auto_20180303_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='characters',
            field=models.ManyToManyField(blank=True, to='content.Character'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.ContextType'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='genre',
            field=models.ManyToManyField(blank=True, to='content.Genre'),
        ),
        migrations.AddField(
            model_name='episodesegment',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Episode'),
        ),
        migrations.AddField(
            model_name='episodesegment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
