# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 10:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20180303_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, to='content.Character'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='content_subject',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='content_synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64, null=True), size=20),
        ),
        migrations.AlterField(
            model_name='episode',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='set_in_location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='telecast_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
