# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20180303_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='characters',
            field=models.ManyToManyField(blank=True, to='content.Character'),
        ),
    ]
