# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20180303_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='keywords',
        ),
    ]
