# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_movie_moviesegment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'permissions': (('view_episode', 'Can view episode'),)},
        ),
        migrations.AlterModelOptions(
            name='episodesegment',
            options={'permissions': (('view_episodesegment', 'Can view episode segment'),)},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': (('view_movie', 'Can view movie'),)},
        ),
        migrations.AlterModelOptions(
            name='moviesegment',
            options={'permissions': (('view_moviesegment', 'Can view movie segment'),)},
        ),
    ]
