# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20180312_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_till', models.DateTimeField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, max_length=256, null=True)),
                ('person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Person')),
            ],
            options={
                'permissions': (('view_actor', 'Can view actor'),),
            },
        ),
    ]
