# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='partner_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
