# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20180412_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Movie'),
        ),
    ]
