# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_trivia_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='movie',
        ),
        migrations.AddField(
            model_name='trivia',
            name='movie',
            field=models.ManyToManyField(to='content.Movie'),
        ),
    ]
