# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-20 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_auto_20180418_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Channel'),
        ),
    ]
