# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-18 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_trivia_original_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='is_approved',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
