# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-28 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_label_playlist_playlistentry_song_trivialog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'permissions': (('view_label', 'Can view label'),)},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'permissions': (('view_playlist', 'Can view playlist'),)},
        ),
        migrations.AlterModelOptions(
            name='playlistentry',
            options={'permissions': (('view_playlistentry', 'Can view playlist entry'),)},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'permissions': (('view_song', 'Can view song'),)},
        ),
        migrations.AlterModelOptions(
            name='trivialog',
            options={'permissions': (('view_trivialog', 'Can view trivia log'),)},
        ),
    ]
