# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_auto_20180628_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistentry',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='playlistentry',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
