# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-02 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_nxsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music_directors',
            field=models.ManyToManyField(related_name='songs_ms_director', to='content.Person'),
        ),
    ]
