# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-04 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_auto_20180704_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='edit_status',
            field=models.CharField(blank=True, choices=[('RIV', 'Review'), ('CLN', 'Clean'), ('ACP', 'Accepted'), ('NCP', 'Not Accepted')], default='CLN', max_length=3, null=True),
        ),
    ]
