# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-18 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0047_auto_20180711_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaEditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trivia_before', models.TextField()),
                ('trivia_after', models.TextField()),
                ('edited_on', models.DateTimeField()),
                ('trivia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Trivia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
