# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-19 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_triviareviewlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviareviewlog',
            name='is_approved_after',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='triviareviewlog',
            name='is_approved_before',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
