# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-15 16:59
from __future__ import unicode_literals

from django.db import migrations
import utils.unique_filename
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_auto_20181010_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='poster',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=utils.unique_filename.unique_upload, verbose_name='Poster'),
        ),
        migrations.AddField(
            model_name='series',
            name='poster_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
