# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-26 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_auto_20181015_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nxsong',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
        migrations.AlterField(
            model_name='song',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='songs_actors', to='content.Person'),
        ),
        migrations.AlterField(
            model_name='song',
            name='music_directors',
            field=models.ManyToManyField(blank=True, related_name='songs_ms_director', to='content.Person'),
        ),
        migrations.AlterField(
            model_name='song',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='songs_producer', to='content.Person'),
        ),
        migrations.AlterField(
            model_name='song',
            name='singers',
            field=models.ManyToManyField(blank=True, related_name='songs_singer', to='content.Person'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_writers',
            field=models.ManyToManyField(blank=True, related_name='songs_writer', to='content.Person'),
        ),
    ]
