# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-28 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_auto_20181026_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'permissions': (('view_channel', 'Can view channel'),)},
        ),
    ]
