# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-01 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_series_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'permissions': (('view_series', 'Can view series'),), 'verbose_name_plural': 'Series'},
        ),
    ]
