# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-31 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0057_channelclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_code',
            field=models.IntegerField(null=True),
        ),
    ]
