# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_channelclip_filled_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
