# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0063_auto_20190702_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='remark',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='remark',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='remark',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
