# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-12 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0064_auto_20190702_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('song', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Song')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_song_verification', 'Can view song verification'),),
            },
        ),
    ]
