# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-03 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0070_auto_20191003_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='user',
        ),
        migrations.AddField(
            model_name='assign',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
