# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0071_auto_20191003_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
