# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-07 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_collection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('start_of_media', models.DateTimeField()),
                ('end_of_media', models.DateTimeField()),
                ('duration', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.AssetVersion')),
            ],
            options={
                'permissions': (('Segment', 'Creates a new segment'),),
            },
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
