# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-08 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.unique_filename
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0073_auto_20191007_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rushes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('year_of_release', models.DateField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('content_subject', models.CharField(blank=True, max_length=128, null=True)),
                ('content_synopsis', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('poster', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=utils.unique_filename.unique_upload, verbose_name='Poster')),
                ('poster_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('cast', models.ManyToManyField(blank=True, to='content.Person')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Channel')),
                ('genre', models.ManyToManyField(blank=True, to='content.Genre')),
            ],
            options={
                'permissions': (('view_movie', 'Can view movie'),),
            },
        ),
    ]
