# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-08 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0074_rushes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rushes',
            options={'permissions': (('view_rushes', 'Can view rushes'),)},
        ),
    ]
