# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-08 08:30
from __future__ import unicode_literals

from django.db import migrations
import utils.unique_filename
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0076_auto_20191108_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='poster',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=utils.unique_filename.unique_upload, verbose_name='Poster'),
        ),
        migrations.AddField(
            model_name='channel',
            name='poster_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
