# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-12-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0078_auto_20191221_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowinstance',
            name='title',
        ),
        migrations.AddField(
            model_name='workflowtransitionhistory',
            name='asset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.AssetVersion'),
        ),
    ]
