# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-12-21 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0080_generictag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generictag',
            name='parent',
        ),
        migrations.DeleteModel(
            name='GenericTag',
        ),
    ]
