# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-27 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0081_auto_20191221_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='metadata_audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.URLField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.CharField(default='english', max_length=128)),
                ('asset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.AssetVersion')),
            ],
            options={
                'permissions': (('view_audiometadata', 'Can view audio_metadata'),),
            },
        ),
    ]
