# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-28 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.unique_filename
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0083_auto_20191227_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('released_on', models.DateField(blank=True, null=True)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('recorded_in', models.CharField(blank=True, max_length=128, null=True)),
                ('genre', models.CharField(blank=True, max_length=128, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=128, null=True)),
                ('duration', models.DateTimeField(null=True)),
                ('tempo', models.CharField(blank=True, max_length=128, null=True)),
                ('lyrics', models.CharField(blank=True, max_length=5000, null=True)),
                ('version', models.CharField(blank=True, max_length=5000, null=True)),
                ('original_remake', models.CharField(blank=True, max_length=5000, null=True)),
                ('poster', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=utils.unique_filename.unique_upload, verbose_name='Poster')),
                ('poster_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('actors', models.ManyToManyField(blank=True, related_name='songsasset_actors', to='content.Person')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Label')),
                ('movie_directors', models.ManyToManyField(blank=True, related_name='songsasset_movie_director', to='content.Person')),
                ('music_directors', models.ManyToManyField(blank=True, related_name='songsasset_ms_director', to='content.Person')),
                ('producers', models.ManyToManyField(blank=True, related_name='songsasset_producer', to='content.Person')),
                ('singers', models.ManyToManyField(blank=True, related_name='songsasset_singer', to='content.Person')),
                ('song_writers', models.ManyToManyField(blank=True, related_name='songsasset_writer', to='content.Person')),
            ],
            options={
                'permissions': (('view_songasset', 'Can view songasset'),),
            },
        ),
    ]
