# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-12-30 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0084_songasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('last_processes', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'permissions': (('view_batch', 'Can view batch'),),
            },
        ),
    ]
