# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-12-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0085_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='last_processes',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
