# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-12-30 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_auto_20191227_0741'),
        ('content', '0086_auto_20191230_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProcessingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hardcuts_processed', models.BooleanField(default=False)),
                ('facedetection_processed', models.BooleanField(default=False)),
                ('facematching_processed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='last_processes',
            new_name='last_created_on',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='is_processed',
            new_name='processed',
        ),
        migrations.AddField(
            model_name='videoprocessingstatus',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Batch'),
        ),
        migrations.AddField(
            model_name='videoprocessingstatus',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
