# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-12-30 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0087_auto_20191230_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocessingstatus',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
