# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-06 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_auto_20191227_0741'),
        ('content', '0088_videoprocessingstatus_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoprocessingstatus',
            options={'permissions': (('view_batch', 'Can view batch'),)},
        ),
        migrations.AddField(
            model_name='videoprocessingstatus',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='promo',
            name='cast',
        ),
        migrations.AddField(
            model_name='promo',
            name='cast',
            field=models.ManyToManyField(blank=True, to='content.Person'),
        ),
        migrations.RemoveField(
            model_name='videoprocessingstatus',
            name='facedetection_processed',
        ),
        migrations.RemoveField(
            model_name='videoprocessingstatus',
            name='facematching_processed',
        ),
        migrations.RemoveField(
            model_name='videoprocessingstatus',
            name='hardcuts_processed',
        ),
        migrations.AlterUniqueTogether(
            name='videoprocessingstatus',
            unique_together=set([('batch', 'video')]),
        ),
    ]
