# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-08 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0089_auto_20200106_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoprocessingstatus',
            options={'permissions': (('view_videoprocessingstatus', 'Can view batch'),)},
        ),
    ]
