# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0090_auto_20200108_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushes',
            name='cast',
            field=models.ManyToManyField(blank=True, null=True, to='content.Person'),
        ),
    ]
