# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-09 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0091_auto_20200109_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocessingstatus',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
