# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-18 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0093_auto_20200117_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='content.Genre'),
        ),
        migrations.AlterField(
            model_name='rushes',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='content.Genre'),
        ),
        migrations.RemoveField(
            model_name='songasset',
            name='genre',
        ),
        migrations.AddField(
            model_name='songasset',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='content.Genre'),
        ),
    ]
