# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-18 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0094_auto_20200118_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_name',
        ),
        migrations.AddField(
            model_name='genre',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Title'),
        ),
    ]
