# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-20 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0096_auto_20200120_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='asset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.AssetVersion'),
        ),
    ]
