# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-20 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0097_sequence_asset_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='version',
        ),
        migrations.AddField(
            model_name='segment',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Sequence'),
        ),
    ]
