# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-20 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0098_auto_20200120_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='name',
            new_name='title',
        ),
    ]
