# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-20 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0099_auto_20200120_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='end_of_media',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='start_of_media',
        ),
    ]
