# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-25 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0101_auto_20200120_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('secondary_title', models.CharField(blank=True, max_length=128)),
                ('short_title', models.CharField(blank=True, max_length=128)),
                ('season_number', models.PositiveIntegerField(blank=True, null=True)),
                ('telecast_date', models.DateField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('content_subject', models.CharField(blank=True, max_length=128, null=True)),
                ('content_synopsis', models.TextField(blank=True, null=True)),
                ('set_in_location', models.CharField(blank=True, max_length=128, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Channel')),
                ('characters', models.ManyToManyField(blank=True, to='content.Character')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.ContextType')),
                ('genre', models.ManyToManyField(blank=True, to='content.Genre')),
            ],
            options={
                'permissions': (('view_season', 'Can view season'),),
            },
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='episode_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='series',
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Series'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Season'),
        ),
    ]
