# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-25 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0102_auto_20200125_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='season',
            name='channel',
        ),
    ]
