# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0105_auto_20200127_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='screenplay',
            field=models.ManyToManyField(blank=True, related_name='season_screenplay', to='content.Person'),
        ),
        migrations.AddField(
            model_name='series',
            name='screenplay',
            field=models.ManyToManyField(blank=True, related_name='series_screenplay', to='content.Person'),
        ),
    ]
