# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-05 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0106_auto_20200127_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='poster_ppoi',
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
