# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0108_auto_20200208_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowinstance',
            options={'permissions': (('view_workflowinstance', 'Can view WorkFlowInstance'),)},
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='asset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.AssetVersion'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='work_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.WorkFlow'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowinstance',
            unique_together=set([('asset_version', 'work_flow')]),
        ),
    ]
