# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-18 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0049_auto_20200218_1146'),
        ('content', '0110_auto_20200208_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='video_metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.VideoProxyPath'),
        ),
    ]
