# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-02-24 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0113_auto_20200219_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='songasset',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Channel'),
        ),
    ]
