# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-17 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0115_auto_20200309_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='is_tagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignassetversion',
            name='asset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='content.AssetVersion'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='asset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_flow_instances', to='content.AssetVersion'),
        ),
        migrations.AlterField(
            model_name='workflowinstancestep',
            name='work_flow_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_flow_instance_steps', to='content.WorkFlowInstance'),
        ),
    ]
