# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-30 11:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0117_assetversion_is_indexed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowInstanceMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('asset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.AssetVersion')),
            ],
            options={
                'permissions': (('view_workflowinstancemembership', 'Can view WorkFlowInstanceMembership'),),
            },
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='allowed_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NS', 'Not Started'), ('REV', 'Review'), ('APR', 'Approve'), ('APE', 'Approve with Edits'), ('REJ', 'Reject'), ('CMP', 'Completed'), ('FAI', 'Failed'), ('PASS', 'Pass')], max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='workflowinstance',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='workflowinstancemembership',
            name='work_flow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.WorkFlowInstance'),
        ),
        migrations.RemoveField(
            model_name='workflowinstance',
            name='asset_version',
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='asset_version',
            field=models.ManyToManyField(blank=True, null=True, related_name='work_flow_instances', through='content.WorkFlowInstanceMembership', to='content.AssetVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowinstancemembership',
            unique_together=set([('asset_version', 'work_flow_instance')]),
        ),
    ]
