# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-30 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0118_auto_20200330_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstancemembership',
            name='work_flow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_to_asset', to='content.WorkFlowInstance'),
        ),
    ]
