# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-01 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0120_auto_20200330_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignWorkFlowInstanceStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('work_flow_instance_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='content.WorkFlowInstanceStep')),
            ],
            options={
                'permissions': (('Assign', 'Assign to user'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='assignassetversion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='assignassetversion',
            name='asset_version',
        ),
        migrations.RemoveField(
            model_name='assignassetversion',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='assignassetversion',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='AssignAssetVersion',
        ),
        migrations.AlterUniqueTogether(
            name='assignworkflowinstancestep',
            unique_together=set([('work_flow_instance_step', 'assigned_to')]),
        ),
    ]
