# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-16 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0126_rushes_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='language',
        ),
        migrations.RemoveField(
            model_name='rushes',
            name='language',
        ),
        migrations.RemoveField(
            model_name='songasset',
            name='language',
        ),
    ]
