# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0093_masterreportgen'),
        ('content', '0127_auto_20200416_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
        migrations.AddField(
            model_name='promo',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
        migrations.AddField(
            model_name='rushes',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
        migrations.AddField(
            model_name='songasset',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
    ]
