# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-16 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0128_auto_20200416_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetversion',
            name='proxy_type',
            field=models.CharField(blank=True, choices=[('SRC', 'Source'), ('ITM', 'Intermediate'), ('MTR', 'Master')], default='SRC', max_length=20, null=True),
        ),
    ]
