# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0131_auto_20200420_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetversion',
            name='aka_title',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='album',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='bitrate',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='codec',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='created_for_month_year',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='dublist_export_date',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='estimated_first_air_date',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='frame_rate',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='height',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='producers',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='production_house',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='production_number',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='size',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='slot_duration',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='total_frames',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='tx_run_time',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='version_title',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='width',
        ),
        migrations.AddField(
            model_name='assetversion',
            name='end_credit_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='end_credit_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='voice_in_ec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assetversion',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
    ]
