# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-22 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0132_auto_20200420_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='timecode_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
