# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-23 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0012_auto_20200419_1233'),
        ('content', '0133_auto_20200422_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workgroups.WorkGroup'),
        ),
    ]
