# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0136_auto_20200425_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetversion',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='assetversion',
            old_name='audio_avaialble',
            new_name='is_audio_available',
        ),
        migrations.RenameField(
            model_name='assetversion',
            old_name='subtitle_avaialble',
            new_name='is_subtitle_available',
        ),
        migrations.RenameField(
            model_name='assetversion',
            old_name='voice_in_ec',
            new_name='is_voice_in_ec',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='audio_languages',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='end_credit_end_time',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='end_credit_start_time',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='format_type',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='subtitle_languages',
        ),
        migrations.AddField(
            model_name='assetversion',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetversion',
            name='version_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
