# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-25 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0138_auto_20200425_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='version_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
