# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-29 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0096_auto_20200423_1618'),
        ('content', '0139_assetversion_version_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercial',
            options={'permissions': (('view_commercial', 'Can view Commercial'),)},
        ),
        migrations.AddField(
            model_name='commercial',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
    ]
