# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-01 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0140_auto_20200429_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='ingested_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rushes',
            name='ingested_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
