# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-04 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0141_auto_20200501_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstancestep',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
