# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-08 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0142_workflowinstancestep_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetversion',
            name='language',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='language',
        ),
        migrations.RemoveField(
            model_name='rushes',
            name='language',
        ),
        migrations.RemoveField(
            model_name='songasset',
            name='language',
        ),
    ]
