# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-08 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0144_auto_20200508_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetversion',
            name='audio_languages',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='language',
        ),
        migrations.RemoveField(
            model_name='assetversion',
            name='subtitle_languages',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='language',
        ),
        migrations.RemoveField(
            model_name='rushes',
            name='language',
        ),
        migrations.RemoveField(
            model_name='songasset',
            name='language',
        ),
    ]
