# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0096_auto_20200423_1618'),
        ('content', '0145_auto_20200508_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='audio_languages',
            field=models.ManyToManyField(blank=True, related_name='assetversion_audio_languages', to='tags.ContentLanguage'),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='subtitle_languages',
            field=models.ManyToManyField(blank=True, related_name='assetversion_subtitle_languages', to='tags.ContentLanguage'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
        migrations.AddField(
            model_name='promo',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
        migrations.AddField(
            model_name='rushes',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
        migrations.AddField(
            model_name='songasset',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage'),
        ),
    ]
