# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-12 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0146_auto_20200508_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignWorkFlowCollectionInstanceStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_assignworkflowcollectioninstancestep', 'Can view AssignWorkFlowCollectionInstanceStep'),),
            },
        ),
        migrations.CreateModel(
            name='WorkFlowCollectionInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'permissions': (('view_workflowcollectioninstance', 'Can view WorkFlowCollectionInstance'),),
            },
        ),
        migrations.CreateModel(
            name='WorkFlowCollectionInstanceStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_flow_step_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_flow_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_flow_instance_steps', to='content.WorkFlowCollectionInstance')),
                ('work_flow_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.WorkFlowStep')),
            ],
            options={
                'permissions': (('view_workflowcollectioninstancestep', 'Can view WorkFlowCollectionInstanceStep'),),
            },
        ),
        migrations.AlterModelOptions(
            name='assignworkflowinstancestep',
            options={'permissions': (('view_assignworkflowinstancestep', 'Can view AssignWorkFlowInstanceStep'),)},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': (('view_collection', 'Can view collection'),)},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='workflow',
        ),
        migrations.AddField(
            model_name='workflowcollectioninstance',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_flow_instances', to='content.Collection'),
        ),
        migrations.AddField(
            model_name='workflowcollectioninstance',
            name='work_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.WorkFlow'),
        ),
        migrations.AddField(
            model_name='assignworkflowcollectioninstancestep',
            name='work_flow_instance_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='content.WorkFlowCollectionInstanceStep'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowcollectioninstancestep',
            unique_together=set([('work_flow_instance', 'work_flow_step')]),
        ),
        migrations.AlterUniqueTogether(
            name='assignworkflowcollectioninstancestep',
            unique_together=set([('work_flow_instance_step', 'assigned_to')]),
        ),
    ]
