# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-18 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0147_auto_20200512_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='cbfc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='movie_directors', to='content.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='dop',
            field=models.ManyToManyField(blank=True, related_name='movie_dop', to='content.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='movie_producer', to='content.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='remark',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenplay',
            field=models.ManyToManyField(blank=True, related_name='movie_screenplay', to='content.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
