# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-19 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.unique_filename
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0098_auto_20200515_0955'),
        ('content', '0148_auto_20200518_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('aka_title', models.CharField(blank=True, max_length=256, null=True)),
                ('house_number', models.CharField(blank=True, max_length=128, null=True)),
                ('product_code', models.CharField(blank=True, max_length=256, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=128, null=True)),
                ('poster', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=utils.unique_filename.unique_upload, verbose_name='Poster')),
                ('poster_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_commercialasset', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.ContentLanguage')),
            ],
            options={
                'permissions': (('view_commercialasset', 'Can view commercialasset'),),
            },
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='language',
        ),
        migrations.DeleteModel(
            name='Commercial',
        ),
    ]
