# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-20 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0150_auto_20200520_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='songasset',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
