# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-20 15:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0151_songasset_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='allowed_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NSD', 'Not Started'), ('REV', 'Review'), ('APR', 'Approve'), ('APE', 'Approve with Edits'), ('REJ', 'Reject'), ('CMP', 'Completed'), ('FAI', 'Failed'), ('PAS', 'Pass'), ('OVE', 'Override')], max_length=100), blank=True, null=True, size=None),
        ),
    ]
