# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-22 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0153_auto_20200521_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songasset',
            name='makers',
        ),
    ]
