# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-25 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0155_auto_20200525_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='production_house',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_number',
        ),
        migrations.RemoveField(
            model_name='songasset',
            name='production_house',
        ),
    ]
