# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-25 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0157_auto_20200525_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialasset',
            name='remark',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='commercialasset',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialasset',
            name='year_of_release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
