# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-07-24 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0160_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
