# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-10-19 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0161_demo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='series',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
