# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-10-20 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0162_auto_20201019_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='ingested_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
