# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-10-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0163_series_ingested_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='part',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
