# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-02-06 17:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0166_auto_20201109_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uniq_id', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
            ],
            options={
                'permissions': (('view_demo', 'Can view demo'),),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128, null=True)),
                ('title', models.CharField(max_length=128, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('file_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('notes', models.CharField(max_length=128, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='content.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=128, null=True)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
                ('title_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='content.Channel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_parent', to='content.Folder')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_folderlocation', to='content.Folder'),
        ),
    ]
