# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-04-04 12:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0170_auto_20220317_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': (('user_view_file', 'User level can view file'), ('team_view_file', 'Team level can view file'), ('org_view_file', 'Org level can view file'), ('user_add_file', 'User level can add file'), ('team_add_file', 'Team level can add file'), ('org_add_file', 'Org level can add file'), ('user_change_file', 'User level can change file'), ('team_change_file', 'Team level can change file'), ('org_change_file', 'Org level can change file'), ('user_delete_file', 'User level can delete file'), ('team_delete_file', 'Team level can delete file'), ('org_delete_file', 'Org level can delete file'))},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'permissions': (('user_view_folder', 'User level can view folder'), ('team_view_folder', 'Team level can view folder'), ('org_view_folder', 'Org level can view folder'), ('user_add_folder', 'User level can add folder'), ('team_add_folder', 'Team level can add folder'), ('org_add_folder', 'Org level can add folder'), ('user_change_folder', 'User level can change folder'), ('team_change_folder', 'Team level can change folder'), ('org_change_folder', 'Org level can change folder'), ('user_delete_folder', 'User level can delete folder'), ('team_delete_folder', 'Team level can delete folder'), ('org_delete_folder', 'Org level can delete folder'))},
        ),
        migrations.AddField(
            model_name='workflowmetadata',
            name='opt_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='workflowmetadata',
            name='placeholder',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
         migrations.AlterModelOptions(
            name='projectfiles',
            options={'permissions': (('user_view_projectfiles', 'User level can view project files'), ('team_view_projectfiles', 'Team level can view project files'), ('org_view_projectfiles', 'Org level can view project files'), ('user_add_projectfiles', 'User level can add project files'), ('team_add_projectfiles', 'Team level can add project files'), ('org_add_projectfiles', 'Org level can add project files'), ('user_change_projectfiles', 'User level can change project files'), ('team_change_projectfiles', 'Team level can change project files'), ('org_change_projectfiles', 'Org level can change project files'), ('user_delete_projectfiles', 'User level can delete project files'), ('team_delete_projectfiles', 'Team level can delete project files'), ('org_delete_projectfiles', 'Org level can delete project files'))},
        ),
        migrations.AlterModelOptions(
            name='projectmetadata',
            options={'permissions': (('user_view_projectmetadata', 'User level can view project metadata'), ('team_view_projectmetadata', 'Team level can view project metadata'), ('org_view_projectmetadata', 'Org level can view project metadata'), ('user_add_projectmetadata', 'User level can add project metadata'), ('team_add_projectmetadata', 'Team level can add project metadata'), ('org_add_projectmetadata', 'Org level can add project metadata'), ('user_change_projectmetadata', 'User level can change project metadata'), ('team_change_projectmetadata', 'Team level can change project metadata'), ('org_change_projectmetadata', 'Org level can change project metadata'), ('user_delete_projectmetadata', 'User level can delete project metadata'), ('team_delete_projectmetadata', 'Team level can delete project metadata'), ('org_delete_projectmetadata', 'Org level can delete project metadata'))},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': (('user_view_projects', 'User level can view project'), ('team_view_projects', 'Team level can view project'), ('org_view_projects', 'Org level can view project'), ('user_add_projects', 'User level can add project'), ('team_add_projects', 'Team level can add project'), ('org_add_projects', 'Org level can add project'), ('user_change_projects', 'User level can change project'), ('team_change_projects', 'Team level can change project'), ('org_change_projects', 'Org level can change project'), ('user_delete_projects', 'User level can delete project'), ('team_delete_projects', 'Team level can delete project'), ('org_delete_projects', 'Org level can delete project'))},
        ),
        migrations.AlterModelOptions(
            name='projectversion',
            options={'permissions': (('user_view_projectversion', 'User level can view projectversion'), ('team_view_projectversion', 'Team level can view projectversion'), ('org_view_projectversion', 'Org level can view projectversion'), ('user_add_projectversion', 'User level can add projectversion'), ('team_add_projectversion', 'Team level can add projectversion'), ('org_add_projectversion', 'Org level can add projectversion'), ('user_change_projectversion', 'User level can change projectversion'), ('team_change_projectversion', 'Team level can change projectversion'), ('org_change_projectversion', 'Org level can change projectversion'), ('user_delete_projectversion', 'User level can delete projectversion'), ('team_delete_projectversion', 'Team level can delete projectversion'), ('org_delete_projectversion', 'Org level can delete projectversion'))},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'permissions': (('user_view_workflow', 'User level can view workflow'), ('team_view_workflow', 'Team level can view workflow'), ('org_view_workflow', 'Org level can view workflow'), ('user_add_workflow', 'User level can add workflow'), ('team_add_workflow', 'Team level can add workflow'), ('org_add_workflow', 'Org level can add workflow'), ('user_change_workflow', 'User level can change workflow'), ('team_change_workflow', 'Team level can change workflow'), ('org_change_workflow', 'Org level can change workflow'), ('user_delete_workflow', 'User level can delete workflow'), ('team_delete_workflow', 'Team level can delete workflow'), ('org_delete_workflow', 'Org level can delete workflow'))},
        ),
        migrations.AlterModelOptions(
            name='workflowinstance',
            options={'permissions': (('user_view_workflowinstance', 'User level can view workflowinstance'), ('team_view_workflowinstance', 'Team level can view workflowinstance'), ('org_view_workflowinstance', 'Org level can view workflowinstance'), ('user_add_workflowinstance', 'User level can add workflowinstance'), ('team_add_workflowinstance', 'Team level can add workflowinstance'), ('org_add_workflowinstance', 'Org level can add workflowinstance'), ('user_change_workflowinstance', 'User level can change workflowinstance'), ('team_change_workflowinstance', 'Team level can change workflowinstance'), ('org_change_workflowinstance', 'Org level can change workflowinstance'), ('user_delete_workflowinstance', 'User level can delete workflowinstance'), ('team_delete_workflowinstance', 'Team level can delete workflowinstance'), ('org_delete_workflowinstance', 'Org level can delete workflowinstance'))},
        ),
        migrations.AlterModelOptions(
            name='workflowinstancestep',
            options={'permissions': (('user_view_workflowinstancestep', 'User level can view workflowinstancestep'), ('team_view_workflowinstancestep', 'Team level can view workflowinstancestep'), ('org_view_workflowinstancestep', 'Org level can view workflowinstancestep'), ('user_add_workflowinstancestep', 'User level can add workflowinstancestep'), ('team_add_workflowinstancestep', 'Team level can add workflowinstancestep'), ('org_add_workflowinstancestep', 'Org level can add workflowinstancestep'), ('user_change_workflowinstancestep', 'User level can change workflowinstancestep'), ('team_change_workflowinstancestep', 'Team level can change workflowinstancestep'), ('org_change_workflowinstancestep', 'Org level can change workflowinstancestep'), ('user_delete_workflowinstancestep', 'User level can delete workflowinstancestep'), ('team_delete_workflowinstancestep', 'Team level can delete workflowinstancestep'), ('org_delete_workflowinstancestep', 'Org level can delete workflowinstancestep'))},
        ),
        migrations.AlterModelOptions(
            name='workflowmetadata',
            options={'permissions': (('user_view_workflowmetadata', 'User level can view workflow metadata'), ('team_view_workflowmetadata', 'Team level can view workflow metadata'), ('org_view_workflowmetadata', 'Org level can view workflow metadata'), ('user_add_workflowmetadata', 'User level can add workflow metadata'), ('team_add_workflowmetadata', 'Team level can add workflow metadata'), ('org_add_workflowmetadata', 'Org level can add workflow metadata'), ('user_change_workflowmetadata', 'User level can change workflow metadata'), ('team_change_workflowmetadata', 'Team level can change workflow metadata'), ('org_change_workflowmetadata', 'Org level can change workflow metadata'), ('user_delete_workflowmetadata', 'User level can delete workflow metadata'), ('team_delete_workflowmetadata', 'Team level can delete workflow metadata'), ('org_delete_workflowmetadata', 'Org level can delete workflow metadata'))},
        ),
    ]
