# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-13 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='url',
        ),
    ]
