# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-13 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0002_remove_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
