# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-07 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('view_comment', 'Can view comment'),)},
        ),
    ]
