# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-13 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180807_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='submit_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
