# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180813_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='submit_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='submit_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
